
CREATE TABLE configuracion_global (
    id NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY,
    clave VARCHAR2(255) NOT NULL,
    valor VARCHAR2(255) NOT NULL,
    descripcion CLOB,
    fecha_modificacion TIMESTAMP,
    usuario_id NUMBER(19,0) NOT NULL,
    CONSTRAINT pk_configuracion_global PRIMARY KEY (id),
    CONSTRAINT uk_config_clave UNIQUE (clave)
);

CREATE TABLE feriados_bloqueos (
    id NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY,
    fecha DATE NOT NULL,
    motivo VARCHAR2(255) NOT NULL,
    afecta_reservas NUMBER(1,0) NOT NULL, 
    CONSTRAINT pk_feriados_bloqueos PRIMARY KEY (id)
);


INSERT INTO configuracion_global (clave, valor, descripcion, fecha_modificacion, usuario_id) 
VALUES ('HORARIO_APERTURA', '08:00', 'Horario oficial de apertura del complejo', CURRENT_TIMESTAMP, 1);

INSERT INTO configuracion_global (clave, valor, descripcion, fecha_modificacion, usuario_id) 
VALUES ('HORARIO_CIERRE', '23:30', 'Horario oficial de cierre del complejo', CURRENT_TIMESTAMP, 1);

INSERT INTO configuracion_global (clave, valor, descripcion, fecha_modificacion, usuario_id) 
VALUES ('DURACION_SLOT_MINUTOS', '60', 'Duración base de los bloques de reserva en las canchas', CURRENT_TIMESTAMP, 1);

INSERT INTO configuracion_global (clave, valor, descripcion, fecha_modificacion, usuario_id) 
VALUES ('ANTICIPACION_CANCELACION_HORAS', '12', 'Horas de anticipación mínima para cancelar una reserva sin penalización', CURRENT_TIMESTAMP, 1);

INSERT INTO configuracion_global (clave, valor, descripcion, fecha_modificacion, usuario_id) 
VALUES ('AFORO_MAXIMO', '500', 'Capacidad máxima total de personas dentro del recinto', CURRENT_TIMESTAMP, 1);

INSERT INTO feriados_bloqueos (fecha, motivo, afecta_reservas) 
VALUES (TO_DATE('2026-09-18', 'YYYY-MM-DD'), 'Feriado Irrenunciable - Fiestas Patrias', 1);

INSERT INTO feriados_bloqueos (fecha, motivo, afecta_reservas) 
VALUES (TO_DATE('2026-09-19', 'YYYY-MM-DD'), 'Feriado Irrenunciable - Fiestas Patrias', 1);

INSERT INTO feriados_bloqueos (fecha, motivo, afecta_reservas) 
VALUES (TO_DATE('2026-12-25', 'YYYY-MM-DD'), 'Navidad - Recinto Cerrado', 1);

INSERT INTO feriados_bloqueos (fecha, motivo, afecta_reservas) 
VALUES (TO_DATE('2027-01-01', 'YYYY-MM-DD'), 'Año Nuevo - Recinto Cerrado', 1);

COMMIT;