
CREATE TABLE configuracion_global (
    id NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY,
    clave VARCHAR2(255) NOT NULL,
    valor VARCHAR2(255) NOT NULL,
    descripcion CLOB,
    fecha_modificacion TIMESTAMP,
    usuario_id NUMBER(19,0) NOT NULL,
    CONSTRAINT pk_configuracion_global PRIMARY KEY (id),
    CONSTRAINT uk_config_clave UNIQUE (clave)
);

CREATE TABLE feriados_bloqueos (
    id NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY,
    fecha DATE NOT NULL,
    motivo VARCHAR2(255) NOT NULL,
    afecta_reservas NUMBER(1,0) NOT NULL, 
    CONSTRAINT pk_feriados_bloqueos PRIMARY KEY (id)
);

INSERT INTO configuracion_global (clave, valor, descripcion, fecha_modificacion, usuario_id) 
VALUES ('HORARIO_APERTURA', '08:00', 'Horario oficial de apertura del complejo', CURRENT_TIMESTAMP, 1);

INSERT INTO configuracion_global (clave, valor, descripcion, fecha_modificacion, usuario_id) 
VALUES ('HORARIO_CIERRE', '23:00', 'Horario oficial de cierre del complejo', CURRENT_TIMESTAMP, 1);

COMMIT;