FROM eclipse-temurin:17-jdk-alpine AS builder
WORKDIR /build

COPY pom.xml .
COPY .mvn ./.mvn
COPY mvnw .
COPY usuarios ./usuarios
COPY reservas ./reservas
COPY pos ./pos
COPY suscripciones ./suscripciones
COPY inventario ./inventario
COPY accesos ./accesos
COPY seguimiento ./seguimiento
COPY reportes ./reportes
COPY configuracion ./configuracion
COPY notificaciones ./notificaciones

WORKDIR /build
RUN sed -i 's/\r//' mvnw
RUN chmod +x mvnw
RUN ./mvnw clean package -DskipTests -pl suscripciones -am

FROM eclipse-temurin:17-jre-alpine
WORKDIR /app

COPY --from=builder /build/suscripciones/target/ms-suscripciones-1.0.0.jar /app/app.jar

EXPOSE 8084
ENTRYPOINT ["java", "-jar", "/app/app.jar"]
