version: '3.8'

services:
  db-mysql:
    image: mysql:8.0
    container_name: db-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: onlyfields_reservas
    ports:
      - "3306:3306"
    networks:
      - onlyfields-network

  ms-reservas:
    build: ./reservas
    container_name: ms-reservas
    ports:
      - "8082:8080" # Postman entra por el 8082, el contenedor usa el 8080
    depends_on:
      - db-mysql
    networks:
      - onlyfields-network

  ms-notificaciones:
    build: ./notificaciones
    container_name: ms-notificaciones
    ports:
      - "8090:8080"
    depends_on:
      - db-mysql
    networks:
      - onlyfields-network

  ms-reportes:
    build: ./reportes
    container_name: ms-reportes
    ports:
      - "8088:8080"
    depends_on:
      - db-mysql
    networks:
      - onlyfields-network

networks:
  onlyfields-network:
    driver: bridge