CREATE TABLE categoria (
    id NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY,
    nombre VARCHAR2(100) NOT NULL,
    descripcion VARCHAR2(255),
    CONSTRAINT pk_categoria PRIMARY KEY (id),
    CONSTRAINT uk_categoria_nombre UNIQUE (nombre)
);

CREATE TABLE producto (
    id NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY,
    nombre VARCHAR2(150) NOT NULL,
    codigo VARCHAR2(50) NOT NULL,
    precio NUMBER(19,2) NOT NULL,
    stock NUMBER(10,0) NOT NULL,
    categoria_id NUMBER(19,0) NOT NULL,
    estado VARCHAR2(20) NOT NULL,
    CONSTRAINT pk_producto PRIMARY KEY (id),
    CONSTRAINT uk_producto_codigo UNIQUE (codigo),
    CONSTRAINT fk_producto_categoria FOREIGN KEY (categoria_id) REFERENCES categoria(id)
);

CREATE TABLE movimiento_stock (
    id NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY,
    producto_id NUMBER(19,0) NOT NULL,
    tipo VARCHAR2(50) NOT NULL,
    cantidad NUMBER(10,0) NOT NULL,
    fecha_hora TIMESTAMP NOT NULL,
    referencia VARCHAR2(255),
    CONSTRAINT pk_movimiento_stock PRIMARY KEY (id),
    CONSTRAINT fk_movimiento_producto FOREIGN KEY (producto_id) REFERENCES producto(id)
);

INSERT INTO categoria (nombre, descripcion) VALUES ('Bebidas', 'Refrescos, aguas e isotonicas');
INSERT INTO categoria (nombre, descripcion) VALUES ('Snacks', 'Galletas, barras y chocolates');
INSERT INTO categoria (nombre, descripcion) VALUES ('Equipamiento', 'Balones, petos y accesorios');

INSERT INTO producto (nombre, codigo, precio, stock, categoria_id, estado) VALUES ('Agua Mineral 500ml', 'BEB-001', 1000, 50, 1, 'ACTIVO');
INSERT INTO producto (nombre, codigo, precio, stock, categoria_id, estado) VALUES ('Bebida Isotonica', 'BEB-002', 1500, 30, 1, 'ACTIVO');
INSERT INTO producto (nombre, codigo, precio, stock, categoria_id, estado) VALUES ('Balon de Futbol N5', 'EQP-001', 15000, 5, 3, 'ACTIVO');

INSERT INTO movimiento_stock (producto_id, tipo, cantidad, fecha_hora, referencia) 
VALUES (1, 'ENTRADA', 50, CURRENT_TIMESTAMP, 'Inventario inicial - Carga de sistema');
INSERT INTO movimiento_stock (producto_id, tipo, cantidad, fecha_hora, referencia) 
VALUES (2, 'ENTRADA', 30, CURRENT_TIMESTAMP, 'Inventario inicial - Carga de sistema');
INSERT INTO movimiento_stock (producto_id, tipo, cantidad, fecha_hora, referencia) 
VALUES (3, 'ENTRADA', 5, CURRENT_TIMESTAMP, 'Inventario inicial - Dotación deportiva base');

COMMIT;