CREATE TABLE plan_suscripcion (
    id NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY,
    nombre VARCHAR2(100) NOT NULL,
    descripcion VARCHAR2(255),
    precio NUMBER(19,2) NOT NULL,
    duracion_meses NUMBER(10,0) NOT NULL,
    estado VARCHAR2(20) NOT NULL,
    CONSTRAINT pk_plan_suscripcion PRIMARY KEY (id),
    CONSTRAINT uk_plan_nombre UNIQUE (nombre)
);

CREATE TABLE suscripcion (
    id NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY,
    usuario_id NUMBER(19,0) NOT NULL,
    plan_id NUMBER(19,0) NOT NULL,
    fecha_inicio TIMESTAMP NOT NULL,
    fecha_fin TIMESTAMP,
    estado VARCHAR2(20) NOT NULL,
    CONSTRAINT pk_suscripcion PRIMARY KEY (id),
    CONSTRAINT fk_suscripcion_plan FOREIGN KEY (plan_id) REFERENCES plan_suscripcion(id)
);

INSERT INTO plan_suscripcion (nombre, descripcion, precio, duracion_meses, estado) 
VALUES ('Bronce', 'Acceso básico a canchas', 15000, 1, 'ACTIVO');

INSERT INTO plan_suscripcion (nombre, descripcion, precio, duracion_meses, estado) 
VALUES ('Plata', 'Acceso premium y descuentos', 25000, 1, 'ACTIVO');

INSERT INTO plan_suscripcion (nombre, descripcion, precio, duracion_meses, estado) 
VALUES ('Oro', 'Acceso total y prioridad de reserva', 40000, 1, 'ACTIVO');

INSERT INTO suscripcion (usuario_id, plan_id, fecha_inicio, fecha_fin, estado) 
VALUES (2, 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP + INTERVAL '30' DAY, 'ACTIVO');

INSERT INTO suscripcion (usuario_id, plan_id, fecha_inicio, fecha_fin, estado) 
VALUES (3, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP + INTERVAL '30' DAY, 'ACTIVO');

COMMIT;
