server:
  port: 8090

spring:
  application:
    name: notificaciones

  # Configuración de la Base de Datos (Oracle Cloud)
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@ONLYFIELDS_HIGH?TNS_ADMIN=C:/Users/dolap/Desktop/Wallet/Wallet_ONLYFIELDS
    username: OF_NOTIFICACIONES
    password: OnlyFields2026

  # Desactivar Docker Compose para evitar errores al arrancar
  docker:
    compose:
      enabled: false

  # Configuración de JPA e Hibernate
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.OracleDialect

  # Configuración de Flyway (Control de versiones)
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    baseline-version: 0
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    url: ${spring.datasource.url}

# Configuración de Logs para ver qué pasa en la consola
logging:
  level:
    org.hibernate: DEBUG
    com.zaxxer.hikari: DEBUG
    java.sql: DEBUG