
server.port=8090
spring.application.name=ms-notificaciones

spring.docker.compose.enabled=false
spring.datasource.url=jdbc:oracle:thin:@ONLYFIELDS_HIGH?TNS_ADMIN=C:/Users/dolap/Wallet/Wallet_ONLYFIELDS

spring.datasource.username=OF_NOTIFICACIONES
spring.datasource.password=OnlyFields2026
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true