spring.application.name=usuarios

# Conexion para el oracle
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@onlyfields_high?TNS_ADMIN=C:/Users/seses/Desktop/GIT/Wallet_ONLYFIELDS
spring.datasource.username=OF_USUARIOS
spring.datasource.password=OnlyFields2026

# config para el JPA y el hibernate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=create_drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties jakarta.persistence.schema-generation.database.action=create-drop

# no se XD
logging.level.org.hibernate=DEBUG
logging.level.com.zaxxer.hikari=DEBUG
logging.level.java.sql=DEBUG

spring.docker.compose.enabled=false
