server:
  port: 8088

spring:
  application:
    name: ms-reportes
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@ONLYFIELDS_HIGH?TNS_ADMIN=C:/Users/dolap/Desktop/Wallet/Wallet_ONLYFIELDS
    username: OF_REPORTES
    password: OnlyFields2026
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.OracleDialect
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect
        format_sql: true
        temp:
          use_jdbc_metadata_defaults: false
  flyway:
    enabled: true
    locations: classpath:db/migration
    table: schema_history_reportes
    baseline-on-migrate: true
    clean-on-validation-error: true 
logging:
  level:
    org.hibernate: DEBUG