CREATE TABLE rol (
                     id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                     nombre VARCHAR2(50) NOT NULL UNIQUE,
                     descripcion VARCHAR2(255)
);

CREATE TABLE usuario (
                         id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         nombre VARCHAR2(100) NOT NULL,
                         email VARCHAR2(150) NOT NULL UNIQUE,
                         password_hash VARCHAR2(255) NOT NULL,
                         estado VARCHAR2(20) DEFAULT 'ACTIVO' NOT NULL,
                         fecha_creacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE usuario_rol (
                             usuario_id NUMBER NOT NULL,
                             rol_id NUMBER NOT NULL,
                             PRIMARY KEY (usuario_id, rol_id),
                             CONSTRAINT fk_ur_usuario FOREIGN KEY (usuario_id) REFERENCES usuario (id),
                             CONSTRAINT fk_ur_rol FOREIGN KEY (rol_id) REFERENCES rol (id)
);